// <auto-generated />
namespace GestionConcours.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class add_column_listAtt_toCandidat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_column_listAtt_toCandidat));
        
        string IMigrationMetadata.Id
        {
            get { return "202004041249239_add_column_listAtt_toCandidat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
