// <auto-generated />
namespace GestionConcours.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class convert_numDossier_toInt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(convert_numDossier_toInt));
        
        string IMigrationMetadata.Id
        {
            get { return "202004042357595_convert_numDossier_toInt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
