// <auto-generated />
namespace GestionConcours.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class changing_councour_to_concour : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changing_councour_to_concour));
        
        string IMigrationMetadata.Id
        {
            get { return "202004021832362_changing_councour_to_concour"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
